// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zovwmlqnrsionbolcpng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvdndtbHFucnNpb25ib2xjcG5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxOTk1NjIsImV4cCI6MjA3MTc3NTU2Mn0.XIX-IwW6dTmGMt7skvGoLhg66RLtLa5cRsWHYk_3TVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});